# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Sikifanso < Formula
  desc "Bootstrap homelab Kubernetes clusters with Cilium and ArgoCD in a single command"
  homepage "https://github.com/sikifanso/sikifanso"
  version "0.3.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/sikifanso/sikifanso/releases/download/v0.3.0/sikifanso_0.3.0_darwin_amd64.tar.gz"
      sha256 "b795299eea2a958bd5224db0490dd865c69542c0cff1bbc68485254d51b4a753"

      define_method(:install) do
        bin.install "sikifanso"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/sikifanso/sikifanso/releases/download/v0.3.0/sikifanso_0.3.0_darwin_arm64.tar.gz"
      sha256 "05550d0be7af2877e809d48bee9fe4e2ab4aef11f97b828c26a1ec795506598a"

      define_method(:install) do
        bin.install "sikifanso"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/sikifanso/sikifanso/releases/download/v0.3.0/sikifanso_0.3.0_linux_amd64.tar.gz"
      sha256 "fcf0084286d3898a37bc36aa7da92f20384bc8bd710f34d0e85bffa76052ce8e"
      define_method(:install) do
        bin.install "sikifanso"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/sikifanso/sikifanso/releases/download/v0.3.0/sikifanso_0.3.0_linux_arm64.tar.gz"
      sha256 "92cd4ba8844bff358baab902a388de7ba1a84f0f155519844a1e64925cab7139"
      define_method(:install) do
        bin.install "sikifanso"
      end
    end
  end
end
