# This file was generated by GoReleaser. DO NOT EDIT.
cask "sikifanso" do
  name "sikifanso"
  desc "Bootstrap homelab Kubernetes clusters with Cilium and ArgoCD in a single command"
  homepage "https://github.com/sikifanso/sikifanso"
  version "0.8.2"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "sikifanso"

  on_macos do
    on_intel do
      url "https://github.com/sikifanso/sikifanso/releases/download/v#{version}/sikifanso_#{version}_darwin_amd64.tar.gz"
      sha256 "d018539c2133a48234f1280e060ab633cc50e29f546cb4c939ddbe42e69504aa"
    end
    on_arm do
      url "https://github.com/sikifanso/sikifanso/releases/download/v#{version}/sikifanso_#{version}_darwin_arm64.tar.gz"
      sha256 "6ee948bcb5ec347b2dfc18bfb3c97e1043762ffdc069eb9399b7f63260dc4c16"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/sikifanso/sikifanso/releases/download/v#{version}/sikifanso_#{version}_linux_amd64.tar.gz"
      sha256 "52055d314b558bbbdbcf0ab77028b7a9b880b74f6e20fdd3467ae69e64843e22"
    end
    on_arm do
      url "https://github.com/sikifanso/sikifanso/releases/download/v#{version}/sikifanso_#{version}_linux_arm64.tar.gz"
      sha256 "d50549eb72c05e8931bd95b3196998f820172b8dc04b18d00a168fae04a1e778"
    end
  end

  # No zap stanza required
end
