# This file was generated by GoReleaser. DO NOT EDIT.
cask "sikifanso" do
  name "sikifanso"
  desc "Bootstrap homelab Kubernetes clusters with Cilium and ArgoCD in a single command"
  homepage "https://github.com/sikifanso/sikifanso"
  version "0.4.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "sikifanso"

  on_macos do
    on_intel do
      url "https://github.com/sikifanso/sikifanso/releases/download/v#{version}/sikifanso_#{version}_darwin_amd64.tar.gz"
      sha256 "39af34ce3de9d4b77fdeb593848586c577ee287875caf82abdb423279be2793b"
    end
    on_arm do
      url "https://github.com/sikifanso/sikifanso/releases/download/v#{version}/sikifanso_#{version}_darwin_arm64.tar.gz"
      sha256 "0259b5ec2c768e27691b3670778c73538e79fe0a56675a701cda82e0e2055540"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/sikifanso/sikifanso/releases/download/v#{version}/sikifanso_#{version}_linux_amd64.tar.gz"
      sha256 "5f8b78a9dbddb1f535482c02c74cc3313d3248c735844603031f642f43112790"
    end
    on_arm do
      url "https://github.com/sikifanso/sikifanso/releases/download/v#{version}/sikifanso_#{version}_linux_arm64.tar.gz"
      sha256 "d6c6d9360e2df0a659e9f5a072e60b9ab0b689689e67e2bd9d5156cd20edaec2"
    end
  end

  # No zap stanza required
end
